# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SampleMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'HydraAsync'
  pod 'KeychainAccess'
  pod 'SwiftyJSON'

  target 'SampleMVVMTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

end
